# @package _global_
ndim: 3
analyse: True
metric_groups: ["disp_metrics", "image_metrics", "seg_metrics"]
gpu:

data:
    data_dir_path: /vol/biomedic2/hq615/PROJECTS/2_mutual_info/data/camcan/malpem_split/test
    modality: mono
    crop_size: [176, 192, 176]
    atlas_path:

defaults:
    - inference_model:
