# @package _global_
defaults:
  - data: brain_camcan
  - network: bspline_net
  - transformation: bspline
  - loss: nmi
  - training: training

meta:
  gpu:
  metric_groups: ["disp_metrics", "image_metrics", "seg_metrics"]
  hparam_metrics: ["loss", "mean_dice", "folding_ratio"]
