# @package _global_
defaults:
  - data: brain_camcan
  - network: unet
  - transformation: dense
  - loss: mse
  - training: training

meta:
  gpu:
  metric_groups: ["disp_metrics", "image_metrics", "seg_metrics"]
  hparam_metrics: ["loss", "mean_dice", "folding_ratio"]
  ml_lvls: 1
