# @package _global_
defaults:
  - data: camcan
  - network: unet
  - transformation: disp
  - loss: mse
  - training: training

meta:
  model_dir:
  gpu: 1
  ver: svf
  metric_groups: ["disp_metrics", "image_metrics", "seg_metrics"]
  best_metrics: ["loss", "mean_dice_mean", "folding_ratio_mean"]
  ml_lvls: 1
